name: Auto Deploy to GAS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run deploy
        env:
          GAS_CREDENTIALS: ${{ secrets.GAS_CREDENTIALS }}
